name: "DockerBuild SpringBoot"

on: 
  workflow_run:
    workflows: ["BuildSetup"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: "Build the project"
      uses: ./.github/actions/build-configured-project
      with:
        build-arguments: createAppDockerImages_springboot -x test