# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "DockerPush"

on:
  workflow_run:
    workflows: ["DockerBuild"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  release:
    types: [ published ]

jobs:
  push_dockerimage_db:
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker - DB Image
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: |
              slabstech/revive-db 
              ghcr.io/${{ github.repository }}

        - name: Build and push Docker image - DB
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  push_dockerimage_client:
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker - Client Image
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: |
              slabstech/revive-client 
              ghcr.io/${{ github.repository }}

        - name: Build and push Docker image - Client
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  push_dockerimage_server:
    push_to_registry:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      steps:
        - name: Check out the repo
          uses: actions/checkout@v3

        - name: Log in to Docker Hub
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker - Server Image
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: |
              slabstech/revive-server 
              ghcr.io/${{ github.repository }}

        - name: Build and push Docker image - Server
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}




      
  #    - name: Log in to Docker Hub
  #      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
  #      with:
  #        username: ${{ secrets.DOCKER_HUB_USERNAME }}
  #        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
  #    
  #    - name: Extract metadata (tags, labels) for Docker
  #      id: meta
  #      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
  #      with:
  #        images: slabstech/revive-db:1.0.1
  #    
  #    - name: Build and push Docker image
  #      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
  #      with:
  #        context: .
  #        file: ./docker/db/Dockerfile
  #        push: true
  #        tags: ${{ steps.meta.outputs.tags }}
  #        labels: ${{ steps.meta.outputs.labels }}