name: "DockerPush Server Dropwizard"
on:
#  workflow_run:
#    workflows: ["DockerBuild Dropwizard"]
#    types:
#      - completed
  push:
    branches:
      - deploy_server_container_to_registry
#    tags:
#      - 'v*'
#  pull_request:
#    types: [opened, reopened, synchronize, ready_for_review]
#  release:
#    types: [ published ]
jobs:
  push_server_image :
    name : Push Docker image to Docker Hub - server
    runs-on : ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo  server
        uses: actions/checkout@v3

      - name: Push to container
        uses: ./github/actions/deploy-container-to-registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          project-name: revive
          service-type: server
          tech-name: dropwizard
          dockerfile-path: ./docker/server/dropwizard/Dockerfile
