# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: "DockerPush Client"

on:
  workflow_run:
    workflows: ["DockerBuild"]
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  release:
    types: [ published ]

jobs:
  push_client_image :

    name: Push Docker image to Docker Hub Client
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo -client
        uses: actions/checkout@v3

      - name: Log in to Docker Hub - client
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry - client
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker - Client Image
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: | 
            slabstech/revive-client-reactjs
            ghcr.io/${{ github.repository }}-client-reactjs

      - name: Build and push Docker image - client
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file : docker/client/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
