name: "DockerPush Server Dropwizard"
on:
#  workflow_run:
#    workflows: ["DockerBuild Dropwizard"]
#    types:
#      - completed
  push:
    branches:
      - main
#    tags:
#      - 'v*'
#  pull_request:
#    types: [opened, reopened, synchronize, ready_for_review]
#  release:
#    types: [ published ]
jobs:
  build-configured-project:
    name : Build the required Image
    runs-on : ubuntu-latest
#    outputs:
#      build_path : {{ steps.deploy.out.build_path}}
    steps:
      - uses: actions/checkout@v3
      - name: "Build the project"
        uses: ./.github/actions/build-configured-project
        with:
          build-deploy-args: createAppDockerImages_dropwizard -x test
  push_server_image :
    name : Push Docker image to Docker Hub - server
    runs-on : ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Push to container
        uses: ./.github/actions/deploy-container-to-registry
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          github-actor: ${{ github.actor }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          project-name: revive
          service-type: server
          tech-name: dropwizard
          dockerfile-path: ./docker/server/dropwizard/Dockerfile
#          build_path : ${{ needs.build-configured-project.outputs.build_path}}
